package model;

public enum TipoSolicitud {
    PRESTAMO_EQUIPO,
    APERTURA_LABORATORIO,
    DUDA_TEMA_CLASE,
    CAMBIO_DE_GRUPO,
    CERTIFICADO_ACADEMICO,
    HOMOLOGACION_INTERNACIONAL,
    CONVENIO_UNIVERSITARIO_EXTERNO
}
